#!/usr/bin/env python3
import os
from pathlib import Path


if __name__ == '__main__':
    root = Path(__file__).parent
    lib = root / 'pytoloka'
    exe = root.joinpath('src', 'main.py')
    os.system(f'PYTHONPATH=$PYTHONPATH:{lib} python {exe}')
