#!/usr/bin/env python3
import os
import sys
from pathlib import Path


if __name__ == '__main__':
    root = Path(__file__).parent
    lib = root / 'pytoloka'
    exe = root.joinpath('src', 'main.py')
    args = ' '.join(sys.argv[1:])
    os.system(f'PYTHONPATH=$PYTHONPATH:{lib} python {exe} {args}')
